export interface Employee {
    name: string,
    email: string,
    phoneNumber: string,
    office: string,
    manager: string,
    orgUnit: string,
    mainText: string,
    gitHub: string,
    twitter: string,
    stackOverflow: string,
    linkedIn: string,
    imagePortraitUrl: string,
    imageWallOfLeetUrl: string,
    highlighted: string,
    published: string,
    primaryRole: string,
    secondaryRole: string,
    area: string,
}